config/routes.rb
Oratio::Application.routes.draw do

  resources :allowed_users

  resources :slide_types
  resources :slideshows do
    resources :slides
    match 'update_rank', :to => 'slideshows#update_rank', :via => :post
  end

  resource :setting
  
  match '/auth/:provider/callback', :to => 'sessions#callback'
  match '/auth/failure', :to => 'sessions#login_failure'
  match '/auth/sign_out', :to => 'sessions#sign_out'
  
  match '/special_slides', :to => 'special_slides#index'
  match '/special_slides/:action', :controller => 'special_slides'

  match '/diagnostics', :to => 'diagnostics#index'
  match '/diagnostics/:action', :controller => 'diagnostics'
 
  root :to => "welcome#index"
  
  # See how all your routes lay out with "rake routes"
  
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/slide.rb
# == Schema Information
# Schema version: 20110322204552
#
# Table name: slides
#
#  id            :integer         not null, primary key
#  content       :text
#  slide_type_id :integer         not null
#  slideshow_id  :integer         not null
#  created_at    :datetime
#  updated_at    :datetime
#

class Slide < ActiveRecord::Base
  belongs_to :slideshow
  belongs_to :slide_type

  default_scope :order => 'rank ASC'

  before_create :add_rank

private

  def add_rank
    self.rank = (Slide.maximum("rank") || -1) + 1
  end

end

app/models/slide_type.rb
# == Schema Information
# Schema version: 20110322204552
#
# Table name: slide_types
#
#  id         :integer         not null, primary key
#  name       :string(255)     not null
#  created_at :datetime
#  updated_at :datetime
#

class SlideType < ActiveRecord::Base

  def is_calendar?
    self.name.downcase == "calendar"
  end

  def is_photos?
    self.name.downcase == "photos"
  end

end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_filter :get_slideshow, :authorize!
  
  # GET /slides
  # GET /slides.xml
  def index
    @slides = @slideshow.slides

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @slides }
    end
  end

  # GET /slides/1
  # GET /slides/1.xml
  def show
    @slide = Slide.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @slide }
    end
  end

  # GET /slides/new
  # GET /slides/new.xml
  def new
    @slide = Slide.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @slide }
    end
  end

  # GET /slides/1/edit
  def edit
    @slide = Slide.find(params[:id])
  end

  # POST /slides
  # POST /slides.xml
  def create
    @slide = Slide.new(params[:slide])
    @slide.slideshow = @slideshow

    respond_to do |format|
      if @slide.save
        format.html { redirect_to(slideshow_slides_path, :notice => 'Slide was successfully created.') }
        format.xml  { render :xml => [@slideshow, @slide], :status => :created, :location => @slide }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @slide.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /slides/1
  # PUT /slides/1.xml
  def update
    @slide = Slide.find(params[:id])

    respond_to do |format|
      if @slide.update_attributes(params[:slide])
        format.html { redirect_to(slideshow_slides_path, :notice => 'Slide was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @slide.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.xml
  def destroy
    @slide = Slide.find(params[:id])
    @slide.destroy

    respond_to do |format|
      format.html { redirect_to(slideshow_slides_path, :notice => 'Slide was successfully destroyed.') }
      format.xml  { head :ok }
    end
  end
  
protected
  
  def get_slideshow
    @slideshow = Slideshow.find_by_id(params[:slideshow_id])
  end
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/slides/_form.html.erb
<%= form_for [@slideshow, @slide] do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :slide_type %><br />
    <%= f.select :slide_type_id, SlideType.all.collect { |type| [type.name, type.id] } %>
  </div>
  <div class="actions">
    <%= f.submit nil, :class => "medium button" %>
  </div>
<% end %>

app/views/slides/edit.html.erb
<% title "Editing slide" %>

<%= render 'form' %>

<%= link_to 'Back', slideshow_slides_path %>

app/views/slides/index.html.erb
<% title "Slides for #{@slideshow.name}" %>

<% actions do %>
  <%= link_to 'New Slide', new_slideshow_slide_path, :class => "medium button" %>
<% end %>

<table class="sortable">
  <tbody>
    <% @slides.each do |slide| %>
      <tr id="<%= slide.id %>" class="slide" rel="<%= slide.rank %>">
        <td>
          <%= slide.title %>
        </td>
        <td class="actions">
          <%= link_to 'Edit', edit_slideshow_slide_path(@slideshow, slide), :class => "button" %>
          <%= link_to 'Destroy', [@slideshow, slide], :class => "red button", :confirm => 'Are you sure?', :method => :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/slides/new.html.erb
<% title "New slide" %>

<%= render 'form' %>

<%= link_to 'Back', slideshow_slides_path %>

app/views/slides/show.html.erb
<p>
  <b>Title:</b>
  <%= @slide.title %>
</p>

<p>
  <b>Content:</b>
  <%= @slide.content %>
</p>

<p>
  <b>Slide type:</b>
  <%= @slide.slide_type.name %>
</p>


<%= link_to 'Edit', edit_slideshow_slide_path(@slideshow, @slide) %> |
<%= link_to 'Back', slideshow_slides_path %>