config/routes.rb
Oratio::Application.routes.draw do

  resources :allowed_users

  resources :slide_types
  resources :slideshows do
    resources :slides
    match 'update_rank', :to => 'slideshows#update_rank', :via => :post
  end

  resource :setting
  
  match '/auth/:provider/callback', :to => 'sessions#callback'
  match '/auth/failure', :to => 'sessions#login_failure'
  match '/auth/sign_out', :to => 'sessions#sign_out'
  
  match '/special_slides', :to => 'special_slides#index'
  match '/special_slides/:action', :controller => 'special_slides'

  match '/diagnostics', :to => 'diagnostics#index'
  match '/diagnostics/:action', :controller => 'diagnostics'
 
  root :to => "welcome#index"
  
  # See how all your routes lay out with "rake routes"
  
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/slide_types_controller.rb
class SlideTypesController < ApplicationController
  before_filter :authorize!
  
  # GET /slide_types
  # GET /slide_types.xml
  def index
    @slide_types = SlideType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @slide_types }
    end
  end

  # GET /slide_types/1
  # GET /slide_types/1.xml
  def show
    @slide_type = SlideType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @slide_type }
    end
  end

  # GET /slide_types/new
  # GET /slide_types/new.xml
  def new
    @slide_type = SlideType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @slide_type }
    end
  end

  # GET /slide_types/1/edit
  def edit
    @slide_type = SlideType.find(params[:id])
  end

  # POST /slide_types
  # POST /slide_types.xml
  def create
    @slide_type = SlideType.new(params[:slide_type])

    respond_to do |format|
      if @slide_type.save
        format.html { redirect_to(slide_types_path, :notice => 'Slide type was successfully created.') }
        format.xml  { render :xml => @slide_type, :status => :created, :location => @slide_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @slide_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /slide_types/1
  # PUT /slide_types/1.xml
  def update
    @slide_type = SlideType.find(params[:id])

    respond_to do |format|
      if @slide_type.update_attributes(params[:slide_type])
        format.html { redirect_to(slide_types_path, :notice => 'Slide type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @slide_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /slide_types/1
  # DELETE /slide_types/1.xml
  def destroy
    @slide_type = SlideType.find(params[:id])
    @slide_type.destroy

    respond_to do |format|
      format.html { redirect_to(slide_types_path, :notice => 'Slide type was successfully destroyed.') }
      format.xml  { head :ok }
    end
  end
end

app/helpers/slide_types_helper.rb
module SlideTypesHelper
end

app/views/slide_types/_form.html.erb
<%= form_for(@slide_type) do |f| %>
  <% if @slide_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide_type.errors.count, "error") %> prohibited this slide_type from being saved:</h2>

      <ul>
      <% @slide_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit nil, :class => "medium button" %>
  </div>
<% end %>

app/views/slide_types/edit.html.erb
<% title "Editing slide type" %>

<%= render 'form' %>

<%= link_to 'Back', slide_types_path %>

app/views/slide_types/index.html.erb
<% title "Listing slide types" %>

<% actions do %>
  <%= link_to 'New Slide type', new_slide_type_path, :class => "medium button" %>
<% end %>

<table>
  <tbody>
    <% @slide_types.each do |slide_type| %>
      <tr>
        <td><%= slide_type.name %></td>
        <td class="actions">
          <%= link_to 'Edit', edit_slide_type_path(slide_type), :class => "button" %>
          <%= link_to 'Destroy', slide_type, :class => "red button", :confirm => 'Are you sure?', :method => :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/slide_types/new.html.erb
<% title "New slide type" %>

<%= render 'form' %>

<%= link_to 'Back', slide_types_path %>

app/views/slide_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @slide_type.name %>
</p>


<%= link_to 'Edit', edit_slide_type_path(@slide_type) %> |
<%= link_to 'Back', slide_types_path %>