config/routes.rb
Oratio::Application.routes.draw do

  resources :allowed_users

  resources :slide_types
  resources :slideshows do
    resources :slides
    match 'update_rank', :to => 'slideshows#update_rank', :via => :post
  end

  resource :setting
  
  match '/auth/:provider/callback', :to => 'sessions#callback'
  match '/auth/failure', :to => 'sessions#login_failure'
  match '/auth/sign_out', :to => 'sessions#sign_out'
  
  match '/special_slides', :to => 'special_slides#index'
  match '/special_slides/:action', :controller => 'special_slides'

  match '/diagnostics', :to => 'diagnostics#index'
  match '/diagnostics/:action', :controller => 'diagnostics'
 
  root :to => "welcome#index"
  
  # See how all your routes lay out with "rake routes"
  
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    if signed_in?
      @slideshows = Slideshow.all
    else
      @slideshows = Slideshow.where(:visible => true)
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% title "Slideshows" %>

<% actions do %>
  <% if signed_in? %>
    <%= link_to 'New Slideshow', new_slideshow_path, :class => "medium button" %>
  <% end %>
<% end %>

<p>Please select a slideshow to view from the list below.</p>

<div class="huge-list">
  <% @slideshows.each do |show| %>
    <div class="<%= cycle "odd", "even" %>">
      <div class="title"><%= link_to show.name, show %></div>
      <div class="desc"><%= show.description %></div>
      <% if signed_in? %>
        <div class="edit-controls">
          <%= link_to "Edit", edit_slideshow_path(show), :class => "button" %>
          <%= link_to "Edit Slides", slideshow_slides_path(show), :class => "button" %>
          <%= link_to "Destroy", show, :class => "red button", :confirm => "Are you sure?", :method => :delete %>
        </div>
      <% end %>
    </div>
  <% end%>
</div>