config/routes.rb
Oratio::Application.routes.draw do

  resources :allowed_users

  resources :slide_types
  resources :slideshows do
    resources :slides
    match 'update_rank', :to => 'slideshows#update_rank', :via => :post
  end

  resource :setting
  
  match '/auth/:provider/callback', :to => 'sessions#callback'
  match '/auth/failure', :to => 'sessions#login_failure'
  match '/auth/sign_out', :to => 'sessions#sign_out'
  
  match '/special_slides', :to => 'special_slides#index'
  match '/special_slides/:action', :controller => 'special_slides'

  match '/diagnostics', :to => 'diagnostics#index'
  match '/diagnostics/:action', :controller => 'diagnostics'
 
  root :to => "welcome#index"
  
  # See how all your routes lay out with "rake routes"
  
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/settings.rb
require 'yaml'

class Settings
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :default_timeout

  validates_numericality_of :default_timeout

  def save()
    filedump = File.open("config/settings.yml", 'w')
    YAML::dump( self, filedump )
    filedump.close()
  end

  def to_yaml_properties
    # Only saves relevant data; not the errors, for example
    %w(@default_timeout)
  end

  def persisted?
    false
  end

  def update(settings)
    @default_timeout = settings['default_timeout']
    if valid?
      @default_timeout = Integer(@default_timeout)
      save()
      true
    else
      false
    end
  end

  def Settings.load()
    YAML::load( File.open("config/settings.yml") )
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authorize!

  # GET /settings/edit
  # GET /settings/edit.xml
  def edit
    @users ||= AllowedUsers.all
    @setting ||= Settings.load

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @setting }
    end
  end

  # PUT /settings
  # PUT /settings.xml
  def update
    @setting ||= Settings.load()

    respond_to do |format|
      if @setting.update(params[:settings])
        format.html { redirect_to(edit_setting_path, :notice => 'Settings were successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { redirect_to(edit_setting_path, :notice => "Settings failed to update.") }
        format.xml  { render :xml => @setting.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for(@setting, :url => { :action => "update" }, :html => { :method => :put }) do |f| %>
  <div class="field">
    <%= f.label :default_timeout %><br />
    <%= f.text_field :default_timeout %>
  </div>
  <div class="actions">
    <%= f.submit nil, :class => "small button", :value => "Edit Settings" %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<% title "Global Settings" %>

<%= stylesheet_link_tag 'settings' %>

<p>The options available for configuration.</p>

<div class="settings-list">
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited the settings from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render "form" %>
</div>

<div class="allowed-users">
  <div class="title">Allowed Users</div>
  <p>The users currently allowed to modify slideshows. <%= link_to "Add a user?", new_allowed_user_path %></p>
  <div class="all-users">
    <% @users.each do |user| %>
       <div class="user-display">
         <div class="name"><%= user.name %></div>
         <div class="username"><%= user.username %></div>
         <div class="controls">
           <%= link_to "Show User", allowed_user_path(user), :class => "button" %>
           <%= link_to "Edit User", edit_allowed_user_path(user), :class => "button" %>
           <%= link_to "Delete User", user, :class => "red button", :method => :delete, :confirm => "Are you sure?" %>
         </div>
       </div>
    <% end %>
  </div>
</div>

app/views/settings/index.html.erb
<% title "Global Settings" %>

<%= stylesheet_link_tag 'settings' %>

<p>The options available for configuration.</p>

<div class="settings-list">
  <%= render "form" %>

  <div class="all-users">
    <% @users.each do |user| %>
       <div class="user-display">
         <div class="user-title"><%= user.name %></div>
         <div class="user-desc"><%= user.username %></div>
         <div class="user-controls">
         </div>
       </div>
    <% end %>
  </div>

  <div class="add-user">

  </div>
  
</div>
  <div class="setting-title">Default Timeout:</div>
  <div class="setting-desc"><%= @settings.default_timeout %></div>

  <div class="setting-title">Allowed Users:</div>